import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { DailySummaryExporter, DailySummaryGenerator, DailySummary } from "./types.js";
import type { Logger } from "../logger.js";

export class FileSystemDailySummaryExporter implements DailySummaryExporter {
  constructor(
    private readonly summaryGenerator: DailySummaryGenerator,
    private readonly logger: Logger
  ) {}

  async exportToFile(date: string, outputDir: string): Promise<string> {
    try {
      // Generate the summary
      const summary = await this.summaryGenerator.generateSummary(date);

      // Ensure output directory exists
      await mkdir(outputDir, { recursive: true });

      // Create filename
      const fileName = `daily-summary-${date}.md`;
      const filePath = join(outputDir, fileName);

      // Format summary as markdown
      const markdownContent = this.formatSummaryAsMarkdown(summary);

      // Write to file
      await writeFile(filePath, markdownContent, 'utf-8');

      this.logger.info({ date, filePath }, "Exported daily summary to file");
      return filePath;
    } catch (error) {
      this.logger.error({ error, date, outputDir }, "Failed to export daily summary");
      throw new Error(`Failed to export daily summary for ${date}: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  private formatSummaryAsMarkdown(summary: DailySummary): string {
    const { date, tickets, sessions, activities, effortBullets } = summary;

    // Convert date to readable format
    const readableDate = new Date(date + 'T00:00:00').toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    const content = `# Daily Summary - ${readableDate}

> **Generated on:** ${new Date().toISOString()}  
> **Date:** ${date}

## 📊 Activity Overview

### Tickets
- **Created:** ${tickets.created}
- **Updated:** ${tickets.updated}
- **Completed:** ${tickets.completed}
- **Deleted:** ${tickets.deleted}

### Sessions
- **Total Sessions:** ${sessions.total}
- **Active Sessions:** ${sessions.unique.length > 0 ? sessions.unique.join(', ') : 'None'}

### Activities
- **Total Actions:** ${activities.total}
- **Actions by Type:**
  - Viewed: ${activities.byAction.viewed}
  - Created: ${activities.byAction.created}
  - Updated: ${activities.byAction.updated}
  - Deleted: ${activities.byAction.deleted}
  - Stage Changed: ${activities.byAction.stage_changed}

## 🎯 Effort Summary

${effortBullets.map(bullet => bullet.startsWith('•') ? bullet : `• ${bullet}`).join('\n')}

## 📈 Productivity Insights

${this.generateInsights(summary)}

---

*This summary was automatically generated by Camelot*
`;

    return content;
  }

  private generateInsights(summary: DailySummary): string {
    const insights: string[] = [];
    const { tickets, activities, sessions } = summary;

    // Productivity insights
    const totalTicketWork = tickets.created + tickets.updated + tickets.completed;
    if (totalTicketWork > 10) {
      insights.push("🔥 **High productivity day** - Significant ticket progress made");
    } else if (totalTicketWork > 5) {
      insights.push("⚡ **Good progress** - Steady ticket work throughout the day");
    } else if (totalTicketWork > 0) {
      insights.push("📝 **Light activity** - Some ticket progress made");
    }

    // Completion rate insights
    if (tickets.completed > 0 && tickets.created > 0) {
      const completionRate = (tickets.completed / (tickets.created + tickets.updated)) * 100;
      if (completionRate >= 50) {
        insights.push(`✅ **Strong completion rate** - ${Math.round(completionRate)}% of worked tickets completed`);
      }
    }

    // Session insights
    if (sessions.total > 3) {
      insights.push("🔄 **Multi-session day** - Work distributed across several sessions");
    } else if (sessions.total === 1) {
      insights.push("🎯 **Focused session** - All work completed in a single session");
    }

    // Activity density insights
    const activityDensity = sessions.total > 0 ? Math.round(activities.total / sessions.total) : 0;
    if (activityDensity > 15) {
      insights.push("⚡ **Intense sessions** - High activity per session");
    } else if (activityDensity > 8) {
      insights.push("📊 **Moderate pace** - Balanced activity across sessions");
    }

    // Default insight if no specific patterns found
    if (insights.length === 0) {
      if (activities.total === 0) {
        insights.push("😴 **Quiet day** - No recorded activity");
      } else {
        insights.push("📋 **Regular activity** - Standard day of ticket management");
      }
    }

    return insights.join('\n\n');
  }
}